spring.application.name=charityconnect
server.port=8081

# MongoDB configuration
# spring.data.mongodb.uri=mongodb://localhost:27017/charityconnect
de.flapdoodle.mongodb.embedded.version=6.0.2

# Multipart
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Mail configuration (Gmail example)
# IMPORTANT: You MUST update these with your real Gmail address and an App Password.
# To create an App Password: Google Account -> Security -> 2-Step Verification -> App Passwords.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hajaarazizi73@gmail.com
spring.mail.password=eufvhcdddgbwlcpc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

## Error pages
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.web.resources.add-mappings=false
spring.messages.basename=messages
spring.messages.encoding=UTF-8
